version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    (): meterhub_common.logger.JSONFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  
  console_json:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]

loggers:
  meterhub_acq:
    level: DEBUG
    handlers: [console]
    propagate: false
  
  meterhub_uploader:
    level: DEBUG
    handlers: [console]
    propagate: false
  
  meterhub_ui:
    level: DEBUG
    handlers: [console]
    propagate: false
